const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
const section=html.match(/<section class="section wrap" aria-label="Новогодние банкеты">[\s\S]*?<\/section>/)[0];
const groups=section.split('<div class="banquet-group">').slice(1);
assert.deepEqual(groups.map(g=>(g.match(/<article class="banquet-card">/g)||[]).length),[3,2,2]);
assert.equal((section.match(/class="banquet-list"/g)||[]).length,3);
assert.doesNotMatch(section,/data-(?:carousel|prev|next)|carousel-track|carousel-controls|\sinert|aria-hidden|is-active|style="/);
assert.match(css,/\.banquet-list\{display:grid;grid-template-columns:minmax\(0,1fr\);gap:36px/);
assert.match(css,/\.banquet-list>\.banquet-card\{position:relative;inset:auto;display:block;[^}]*height:auto/);
assert.match(css,/\.banquet-list \.banquet-media\{[^}]*height:430px[^}]*object-fit:cover/);
assert.match(html,/class="carousel dinner-carousel" data-dinner-carousel/);
assert.equal((html.match(/data-dinner-carousel/g)||[]).length,1);
assert.match(css,/\.dinner-carousel \.dinner-card\.is-active\{display:block\}/);
assert.equal(fs.readFileSync(path.join(root,'page-content.html'),'utf8').trim(),html.match(/<main class="new-year-page">[\s\S]*?<\/main>/)[0]);
assert.equal(fs.readFileSync(path.join(root,'patch-banquets/banquets-section.html'),'utf8').trim(),section);
assert.ok(css.endsWith(fs.readFileSync(path.join(root,'patch-banquets/banquets-static.css'),'utf8')));
console.log('PASS: 7 static banquets in 3/2/2 groups, no slider hooks; full and partial source match demo');
