const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { execFileSync } = require('node:child_process');
const root = __dirname;
const { renderGallery } = require('./gallery.cjs');
const galleries = JSON.parse(fs.readFileSync(path.join(root, 'galleries.json'), 'utf8'));
const html = fs.readFileSync(path.join(root, 'embed.html'), 'utf8').replace(/<!-- kfn-gallery:([a-z]+) -->[\s\S]*?<!-- \/kfn-gallery:\1 -->/g,
  (_, key) => `<!-- kfn-gallery:${key} -->\n${renderGallery(key, galleries[key])}\n<!-- /kfn-gallery:${key} -->`);
fs.writeFileSync(path.join(root, 'embed.html'), html);
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const guide = fs.readFileSync(path.join(root, 'INTEGRATION.md'), 'utf8');
const publicAssets = '/upload/katun-food/assets/';
const cmsHtml = html.replaceAll('src="assets/', 'src="' + publicAssets);
const cmsCss = css.replaceAll('url("assets/', 'url("' + publicAssets);
const head = '<!doctype html>\n<html lang="ru">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<meta name="robots" content="noindex,nofollow">\n<meta name="theme-color" content="#4f806d">\n<title>Питание в санатории «Катунь»</title>\n<meta name="description" content="Питание в санатории «Катунь»: персональный рацион, продукты собственного производства и четыре формата питания.">\n<link rel="stylesheet" href="styles.css?v=cms-20260928">\n</head>\n<body>\n';
fs.writeFileSync(path.join(root, 'index.html'), head.replace('cms-20260928', 'arrows-only-20261001') + html + '\n</body>\n</html>\n');
fs.mkdirSync(path.join(root, 'cms'), { recursive: true });
fs.writeFileSync(path.join(root, 'cms', 'katun-food.html'), cmsHtml);
fs.writeFileSync(path.join(root, 'cms', 'katun-food.css'), cmsCss);
fs.writeFileSync(path.join(root, 'cms', 'README.md'), guide);
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'katun-food-cms-'));
fs.writeFileSync(path.join(temp, 'katun-food.html'), cmsHtml);
fs.writeFileSync(path.join(temp, 'katun-food.css'), cmsCss);
fs.writeFileSync(path.join(temp, 'README.md'), guide);
fs.cpSync(path.join(root, 'assets'), path.join(temp, 'assets'), { recursive: true, filter: source => !source.endsWith('.DS_Store') });
execFileSync('zip', ['-qr', path.join(temp, 'katun-food-cms.zip'), 'katun-food.html', 'katun-food.css', 'README.md', 'assets'], { cwd: temp });
fs.copyFileSync(path.join(temp, 'katun-food-cms.zip'), path.join(root, '..', 'downloads', 'katun-food-cms.zip'));
fs.rmSync(temp, { recursive: true, force: true });
console.log('Built demo, CMS HTML/CSS and downloads/katun-food-cms.zip');
